project:
  type: default
  render:
    - index.qmd
  brand: _brand.yml

format:
  revealjs:
    theme: [dark, theme/custom.scss, brand]
    slide-number: true
    preview-links: auto
    transition: slide
    transition-speed: default
    background-transition: fade
    auto-animate: true
    fragment: true
    chalkboard: false
    footer: "Migrating Languages: Choose the Easiest API"
    logo: ""
